apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbna-outbound-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: dbna-outbound.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dbna-outbound
            port:
              name: http
  tls:
  - hosts:
    - dbna-outbound.example.com
    secretName: dbna-outbound-tls

