apiVersion: v1
kind: Secret
metadata:
  name: dbna-outbound-secrets
type: Opaque
stringData:
  KEYSTORE_PATH: "/app/config/keystore.jks"
  KEYSTORE_PASSWORD: "changeit"
  KEY_ALIAS: "dbna"
  KEY_PASSWORD: "changeit"
  DBNA_FROM_PARTY_ID: "your-party-id"
  DBNA_SERVICE_TYPE: ""
  MAVEN_REGISTRY_URL: ""
  MAVEN_REGISTRY_USER: ""
  MAVEN_REGISTRY_PASS: ""

